-- скрипт для урока 61
-- работаем на основе проекта spring_hibernate

create table if not exists Person(
    id int generated by default as identity primary key,
    name varchar,
    age int,
    email varchar
);

insert into Person(name, age, email) values
    ('Иванов Иван Иванович', 15, 'email1@mail.com'),
    ('Петров Петр Петрович', 20, 'email2@mail.com'),
    ('Филимонов Сергей Григорьевич', 25, 'email2@mail.com');