/*
56 Отношение many-to-many в Hibernate
*/
create table Actor(
    id int generated by default as identity primary key,
    name varchar(100) not null unique,
    age int check (age > 0)
);

create table Movie(
    id int generated by default as identity primary key,
    name varchar(200) not null,
    year_of_production int check(year_of_production > 1900)

);

create table Actor_Movie(
    actor_id int references Actor(id),
    movie_id int references Movie(id),
    primary key (actor_id, movie_id)
);