/*
Скрипты SQL для урока 52 One-to-Many в Hibernate
*/
create table Person(
    id int primary key generated by default as identity,
    name varchar(100) not null,
    age int check(age < 100)
);

create table Item(
    id int primary key generated by default as identity,
    person_id int references Person(id) on delete set null,
    item_name varchar(100) not null
);

insert into Person(name, age)  values
    ('Tom', 35),
    ('Bob', 52),
    ('Katy', 14);

insert into Item(person_id, item_name) values
    (1, 'Book'),
    (1, 'AirPods'),
    (2, 'Iphone'),
    (3, 'Kindle'),
    (3, 'TV'),
    (3, 'Playstation');

/* очистить таблицу и обнуть счетчик*/
truncate Item restart identity;
