/*
55 Отношение one-to-one в Hibernate
*/
create table Person(
    id int primary key generated by default as identity,
    name varchar(100) not null,
    age int
);

create table Passport(
    person_id int primary key references Person(id) on delete cascade,
    passport_number int not null
);

/*
 Альтернативный способ создать отношение
 one-to-one на Passport c помощью UNIQUE
 */
create table Passport(
    id int primary key generated by default as identity,
    passport_number int not null,
    person_id int UNIQUE references Person(id) on delete cascade
);