-- 63 Дата и время в Hibernate
create table if not exists Person(
  id int generated by default as identity primary key,
  name varchar,
  age int,
  email varchar
);
-- просто дата без точного времени ( например 03/04/2000)
alter table Person add column date_of_birth date;

/*
Точное время.
Значения timestamp сохраняются в секундах
до или после полуночи 1 января 2000 г.
Поле (колонка) время создания записи
*/
alter table Person add column created_at timestamp;

